[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "object_tracking_training_utils"
version = "0.1.0"
description = "A Python toolkit for training and evaluating object tracking models"
readme = "README.rst"
authors = [
  {name = "Alyssia Fourali", email = "alyssia.fourali.etu@univ-lille.fr"}
]
maintainers = [
  {name = "Alyssia Fourali", email = "alyssia.fourali.etu@univ-lille.fr"}
]
classifiers = [

]
license = {text = "MIT license"}
dependencies = [
  
]

[project.optional-dependencies]
dev = [
    "coverage",  # testing
    "mypy",  # linting
    "pytest",  # testing
    "ruff"  # linting
]

[project.urls]

bugs = "https://github.com/alyssia-fourali/object_tracking_training_utils/issues"
changelog = "https://github.com/alyssia-fourali/object_tracking_training_utils/blob/master/changelog.md"
homepage = "https://github.com/alyssia-fourali/object_tracking_training_utils"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["*.*"]




# Mypy
# ----

[tool.mypy]
files = "."

# Use strict defaults
strict = true
warn_unreachable = true
warn_no_return = true

[[tool.mypy.overrides]]
# Don't require test functions to include types
module = "tests.*"
allow_untyped_defs = true
disable_error_code = "attr-defined"

